name: Swift CI Workflow

on:
  pull_request:
    branches: main

defaults:
  run:
    working-directory: .  # 作業ディレクトリを指定

jobs:
  swift-ci:
    runs-on: macos-latest

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # ツールのインストール
      - name: Install Tools
        run: brew install swiftformat swiftlint

      # SwiftFormatの実行
      - name: Run SwiftFormat(Check Only)
        run: swiftformat . --config .swiftformat --dryrun --lint

      # SwiftLintの実行
      - name: Run SwiftLint
        run: swiftlint --config .swiftlint.yml
